(("default"   . ((user-emacs-directory   . "~/.emacs.d.doom")
                 (env . (("DOOMDIR"      . "~/.doom.d")))))
 ("doom"      . ((user-emacs-directory   . "~/.emacs.d.doom")
                 (env . (("DOOMDIR"      . "~/.doom.d")))))
 ("gnu"        . ((user-emacs-directory   . "~/.emacs.d.gnu"))))
